pcbuilder/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls')),
]

quiz/urls.py
from django.urls import path, reverse
from .views import HomeView, PcBuilderView

app_name = 'quiz'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('pc-builder/', PcBuilderView.as_view(), name='quiz')
]

quiz/models.py
from django.db import models

TAG_CHOICES = (
    ('Core', 'C'),
    ('Speed', 'S'),
    ('Both', 'B')
)

SOCKET_CHOICES = (
    ('AM4', 'AM4'),
    ('1151', '1151'),
    ('2066', '2066'),
    ('TR4', 'TR4'), 
)

TYPE_CHOICES = (
    ('SSD', 'SSD'),
    ('HDD', 'HDD'),
)

SIZE_CHOICES = (
    ('M.2', 'M.2'),
    ('2.5', '2.5'),
    ('PCIe Card', 'PCIe'),
    ('3.5', '3.5'),
)

CHIPSET_CHOICES = (
    ('AMD', 'AMD'),
    ('Nvidia', 'Nvidia')
)

MEMORY_CHOICES = (
    ('GDDR5', 'GDDR5'),
    ('GDDR5X', 'GDDR5X'),
    ('GDDR6', 'GDDR6'),
    ('HBM2', 'HBM2'),
)

GPU_CHOICES = (
    ('Thermals', 'Thermals'),
    ('Performance', 'Perf'),
    ('Price', 'Price')
)

COOLER_SIZE_CHOICES = (
    ('120mm', '120mm'),
    ('140mm', '140mm'),
    ('240mm', '240mm'),
    ('280mm', '280mm'),
    ('Μικρή', 'Μικρή'),
    ('Μεσαία', 'Μεσαία'),
    ('Μεγάλη', 'Μεγάλη'),
)

COOLER_TYPE_CHOICES = (
    ('Απλή χρήση', 'Απλή χρήση'),
    ('Ελαφρύ OC', 'Ελαφρύ OC'),
    ('OC', 'OC')
)

MB_SIZE_CHOICES = (
    ('ATX', 'ATX'),
    ('m-ATX', 'm-ATX'),
    ('mini-ITX', 'mini-ITX')
)

CASE_TYPE_CHOICES = (
    ('Airflow', 'A'),
    ('Silence', 'S'),
    ('Normal', 'N')
)

CERTIFICATE_CHOICES = (
    ('None', 'N'),
    ('80+', '80+'),
    ('Bronze', 'B'),
    ('Silver', 'S'),
    ('Gold', 'G'),
    ('Platinum', 'P'),
    ('Titanium', 'T')
)

MODULAR_CHOICES = (
    ('Full Modular', 'FM'),
    ('Semi Modular', 'SM'),
    ('Full Wired', 'FW')
)

MB_OC_CHOICES = (
    ('None', 'N'),
    ('Normal-OC', 'N-OC'),
    ('OC', 'OC')
)

QUESTION_CHOICES = (
    ('Γενικές', 'Γενικές'),
    ('Ερωτήσεις επεξεργαστή', 'Ερωτήσεις επεξεργαστή'),
    ('Ερωτήσεις μητρικής', 'Ερωτήσεις μητρικής'),
    ('Ερωτήσεις ψύξης', 'Ερωτήσεις ψύξης'),
    ('Ερωτήσεις μνήμης', 'Ερωτήσεις μνήμης'),
    ('Ερωτήσεις κάρτας γραφικών', 'Ερωτήσεις κάρτας γραφικών'),
    ('Ερωτήσεις δίσκου', 'Ερωτήσεις δίσκου'),
    ('Ερωτήσεις τροφοδοτικού', 'Ερωτήσεις τροφοδοτικού'),
    ('Ερωτήσεις κουτιού', 'Ερωτήσεις κουτιού')
)

class Cpu(models.Model):
    name = models.CharField(max_length=50)
    brand = models.CharField(max_length=5)
    oc = models.BooleanField()
    igpu = models.BooleanField()
    price = models.FloatField()
    speed = models.FloatField()
    tag = models.CharField(max_length=5, choices=TAG_CHOICES)
    socket = models.CharField(max_length=4, choices=SOCKET_CHOICES)
    cores = models.IntegerField()
    threads = models.IntegerField()
    tdp = models.IntegerField()
    def __str__(self):
        return self.name

class Disk(models.Model):
    name = models.CharField(max_length=50)
    brand = models.CharField(max_length=50)
    size = models.CharField(max_length=9, choices=SIZE_CHOICES)
    type = models.CharField(max_length=3, choices=TYPE_CHOICES)
    capacity = models.IntegerField()
    rpm = models.IntegerField(blank=True, null=True)
    price = models.FloatField()
    def __str__(self):
        return self.name
    
class Gpu(models.Model):
    name = models.CharField(max_length=50)
    brand = models.CharField(max_length=50)
    price = models.FloatField()
    memory = models.IntegerField()
    chipset = models.CharField(max_length=6, choices=CHIPSET_CHOICES)
    memoryType = models.CharField(max_length=6, choices=MEMORY_CHOICES)
    tag = models.CharField(max_length=11, choices=GPU_CHOICES)
    tdp = models.IntegerField()
    def __str__(self):
        return self.name

class Ram(models.Model):
    name = models.CharField(max_length=50)
    brand = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    capacity = models.IntegerField()
    type = models.CharField(max_length=4, default='DDR4')
    modules = models.IntegerField()
    price = models.FloatField()
    frequency = models.IntegerField()
    CAS = models.IntegerField()
    def __str__(self):
        return self.name

class Cooler(models.Model):
    name = models.CharField(max_length=50)
    brand = models.CharField(max_length=50)
    type = models.CharField(max_length=10, choices=COOLER_TYPE_CHOICES)
    price = models.FloatField()
    size = models.CharField(max_length=6, choices=COOLER_SIZE_CHOICES)
    noise = models.FloatField(blank=True, null=True)
    def __str__(self):
        return self.name

class Case(models.Model):
    name = models.CharField(max_length=50)
    brand = models.CharField(max_length=50)
    price = models.FloatField()
    mbSize = models.CharField(max_length=8, choices=MB_SIZE_CHOICES)
    RGB = models.BooleanField()
    window = models.BooleanField()
    type = models.CharField(max_length=7, choices=CASE_TYPE_CHOICES)
    def __str__(self):
        return self.name

class PSU(models.Model):
    name = models.CharField(max_length=50)
    brand = models.CharField(max_length=50)
    price = models.FloatField()
    watt = models.IntegerField()
    certificate = models.CharField(max_length=8, choices=CERTIFICATE_CHOICES)
    modular = models.CharField(max_length=12, choices=MODULAR_CHOICES)
    def __str__(self):
        return self.name

class MB(models.Model):
    name = models.CharField(max_length=50)
    brand = models.CharField(max_length=50)
    price = models.FloatField()
    size = models.CharField(max_length=8, choices=MB_SIZE_CHOICES)
    socket = models.CharField(max_length=4, choices=SOCKET_CHOICES)
    chipset = models.CharField(max_length=9)
    oc = models.CharField(max_length=10, choices=MB_OC_CHOICES)
    memory_slots = models.IntegerField()
    wifi = models.BooleanField()
    m_2slots = models.IntegerField()
    sata = models.IntegerField()
    usb = models.IntegerField()
    def __str__(self):
        return self.name

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    tag = models.CharField(max_length=25, choices=QUESTION_CHOICES)
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices')
    choice_text = models.CharField(max_length=200)

    def __str__(self):
        return self.choice_text

quiz/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import Cpu, Gpu, Question, Choice

# Create your views here.
class HomeView(TemplateView):
    template_name = "quiz/home.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['cpu'] = Cpu.objects.all()[:8].values()
        context['gpu'] = Gpu.objects.all()[:8].values()
        return context

class PcBuilderView(TemplateView):
    template_name = "quiz/quiz.html"
    questions = Question.objects.all()
    def get_context_data(self, **kwargs):
        context = super(PcBuilderView, self).get_context_data(**kwargs)
        context['questions'] = Question.objects.all()
        return context

quiz/templates/quiz/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/quiz.css' %}" rel="stylesheet">
  <style>
    div.hr {
      margin-top: 40px;
      margin-bottom: 40px;
      border: 0;
      border-top: 2px solid #eee;
      text-align: center;
      height: 0px;
      line-height: 0px;
    }

    .hr-title {
      background-color: #fff;
      font-size: 25px;
    }
  </style>
</head>

<body>

  {% include "quiz/navbar.html" %}

  <!--Main layout-->
  {% block content %}
  {% endblock content %}

  {% block extra_body %}
  {% endblock %}
  <!--Main layout-->

  <!--Footer-->
  {% include "quiz/footer.html" %}
  <!--/.Footer-->

  {% include "quiz/scripts.html" %}

  {% block extra_scripts %}
  {% endblock extra_scripts %}
</body>

</html>

quiz/templates/quiz/footer.html
<footer id="footer" class="pt-4 page-footer text-center font-small mdb-color darken-2 mt-4 wow fadeIn">
    <!-- Social icons -->
    <div class="pb-4">
      <a href="#" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      PCB Corporation
    </div>
    <!--/.Copyright-->

  </footer>

quiz/templates/quiz/home.html
{% extends "quiz/base.html" %}

{% block content %}
<main class="mt-5 pt-5">
    <div class="container">

      <!--Section: Jumbotron-->
      
      <!--Section: Jumbotron-->

      <!--Section: Magazine v.1-->
      <section class="wow fadeIn">

        <!--Section heading-->
        <h2 class="h1 text-center my-5 font-weight-bold">Hottest Products</h2>

        <div class='hr'>
          <span class='hr-title'><strong>Processors</strong></span>
        </div>

        <div class="row text-left">
          {% for item in cpu %}
          <div class="col-lg-6 col-md-12">
          {% if forloop.counter <= 2 %}
            <!--Grid column-->
            <!-- Card deck -->
              <div class="card-deck">

                <!-- Card -->
                <div class="card mb-4">

                  <!--Card image-->
                  <div class="view overlay">
                    <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/16.jpg"
                      alt="Card image cap">
                    <a href="#!">
                      <div class="mask rgba-white-slight"></div>
                    </a>
                  </div>

                  <!--Card content-->
                  <div class="card-body">

                    <!--Title-->
                    <h4 class="card-title">{{ item.name }}</h4>
                    <!--Text-->
                    <h6 style="color: #747373;">Clock Speed: {{ item.speed }} Ghz</h6>
                    <h6 style="color: #747373;">Πυρήνες: {{ item.cores }}, Threads: {{ item.threads }}</h6>
                    <h6 style="color: #747373;">Τιμή: {{ item.price }}€</h6>
                    <p class="card-text">Περιγραφή: Some quick example text to build on the card title and make up the bulk of the card's
                      content.</p>
                    <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
                    <button type="button" class="btn btn-light-blue btn-md">Read more</button>

                  </div>

                </div>
              </div>
              <!-- Card -->
            <!--Grid column-->
          {% else %}
              <hr>
              <!--Small news-->
              <div class="row">
                <div class="col-md-3">

                  <!--Image-->
                  <div class="view overlay rounded z-depth-1">
                    <img src="https://mdbootstrap.com/img/Photos/Others/photo11.jpg" class="img-fluid" alt="Minor sample post image">
                    <a>
                      <div class="mask rgba-white-slight"></div>
                    </a>
                  </div>
                </div>

                <!--Excerpt-->
                <div class="col-md-9">
                  <h5 class="dark-grey-text">
                    <u>{{ item.name }}</u>
                  </h5>
                  <a>Τιμή: {{ item.price }}€, Πυρήνες: {{ item.cores }}, Threads: {{ item.threads}}
                    <i class="fas fa-angle-right float-right"></i>
                  </a>
                </div>

              </div>
              {% endif %}
          </div>
          {% endfor %}
        </div>
        <div class='hr mt-5'>
          <span class='hr-title'><strong>Graphics Cards</strong></span>
        </div>
        <div class="row text-left">
          {% for item in gpu %}
          <div class="col-lg-6 col-md-12">
          {% if forloop.counter <= 2 %}
            <!--Grid column-->
            <!-- Card deck -->
              <div class="card-deck">

                <!-- Card -->
                <div class="card mb-4">

                  <!--Card image-->
                  <div class="view overlay">
                    <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/16.jpg"
                      alt="Card image cap">
                    <a href="#!">
                      <div class="mask rgba-white-slight"></div>
                    </a>
                  </div>

                  <!--Card content-->
                  <div class="card-body">

                    <!--Title-->
                    <h4 class="card-title">{{ item.name }}</h4>
                    <!--Text-->
                    <h6 style="color: #747373;">Τύπος Μνήμης: {{ item.memoryType }}</h6>
                    <h6 style="color: #747373;">Μνήμη: {{ item.memory }}GB</h6>
                    <h6 style="color: #747373;">Τιμή: {{ item.price }}€</h6>
                    <p class="card-text">Περιγραφή: Some quick example text to build on the card title and make up the bulk of the card's
                      content.</p>
                    <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
                    <button type="button" class="btn btn-light-blue btn-md">Read more</button>

                  </div>

                </div>
              </div>
              <!-- Card -->
            <!--Grid column-->
          {% else %}
              <hr>
              <!--Small news-->
              <div class="row">
                <div class="col-md-3">

                  <!--Image-->
                  <div class="view overlay rounded z-depth-1">
                    <img src="https://mdbootstrap.com/img/Photos/Others/photo11.jpg" class="img-fluid" alt="Minor sample post image">
                    <a>
                      <div class="mask rgba-white-slight"></div>
                    </a>
                  </div>
                </div>

                <!--Excerpt-->
                <div class="col-md-9">
                  <h5 class="dark-grey-text">
                    <u>{{ item.name }}</u>
                  </h5>
                  <a>Τιμή: {{ item.price }}€, Μνήμη: {{ item.memory }}GB
                    <i class="fas fa-angle-right float-right"></i>
                  </a>
                </div>

              </div>
              {% endif %}
          </div>
          {% endfor %}
        </div>
      </div>
      </section>
      <!--/Section: Magazine v.1-->


    </div>
</main>
{% endblock content %}

quiz/templates/quiz/navbar.html
  <!--Main Navigation-->
  <header>
    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
        <div class="container">
  
          <!-- Brand -->
          <a class="navbar-brand waves-effect" href="{% url 'quiz:home' %}">
            <strong class="blue-text">PCB</strong>
          </a>
  
          <!-- Collapse -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
  
          <!-- Links -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
  
            <!-- Left -->
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link waves-effect" href="#">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link waves-effect" href="#">PC Builder Quiz</a>
              </li>
            </ul>
  
            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">
              <li class="nav-item mr-2">
                <a href="#" class="nav-link border border-light rounded waves-effect" target="_blank">
                  <i class="fab fa-facebook-f"></i>Facebook
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link border border-light rounded waves-effect" target="_blank">
                  <i class="fab fa-youtube"></i>Youtube
                </a>
              </li>
            </ul>
  
          </div>
  
        </div>
      </nav>
      <!-- Navbar -->
    </header>
    <!--Main Navigation-->      

quiz/templates/quiz/quiz.html
{% extends "quiz/base.html" %}

{% block content %}
<main class="mt-5 pt-5 mb-5">
<div class="container-fluid ">
    <div class="modal-dialog">
        <div class="modal-content">
            {% for question in questions %}
            <div class="modal-header">
                <h3><span class="label label-warning" id="qid">{{ question.pk }}</span> {{ question.question_text }}</h3>
            </div>
            <div class="modal-body">
                {% for choice in question.choices.all %}
                    <label class="element-animation1 btn btn-lg btn-primary btn-block"><div class="d-flex align-items-center btn-label"><i class="fas fa-chevron-right"></i></div> <input type="radio" name="q_answer" value="1">{{ choice.choice_text }}</label>    
                {% endfor %}  
                        
                    
                <!-- <div class="col-xs-3 col-xs-offset-5">
                <div id="loadbar" style="display: none;">
                        <div class="blockG" id="rotateG_01"></div>
                        <div class="blockG" id="rotateG_02"></div>
                        <div class="blockG" id="rotateG_03"></div>
                        <div class="blockG" id="rotateG_04"></div>
                        <div class="blockG" id="rotateG_05"></div>
                        <div class="blockG" id="rotateG_06"></div>
                        <div class="blockG" id="rotateG_07"></div>
                        <div class="blockG" id="rotateG_08"></div>
                    </div>
                </div>

                <div class="quiz" id="quiz" data-toggle="buttons">
                    <label class="element-animation1 btn btn-lg btn-primary btn-block"><div class="d-flex align-items-center btn-label"><i class="fas fa-chevron-right"></i></div> <input type="radio" name="q_answer" value="1">1 One</label>
                    <label class="element-animation2 btn btn-lg btn-primary btn-block"><div class="d-flex align-items-center btn-label"><i class="fas fa-chevron-right"></i></div> <input type="radio" name="q_answer" value="2">2 Two</label>
                    <label class="element-animation3 btn btn-lg btn-primary btn-block"><div class="d-flex align-items-center btn-label"><i class="fas fa-chevron-right"></i></div> <input type="radio" name="q_answer" value="3">3 Three</label>
                    <label class="element-animation4 btn btn-lg btn-primary btn-block"><div class="d-flex align-items-center btn-label"><i class="fas fa-chevron-right"></i></div> <input type="radio" name="q_answer" value="4">4 Four</label>
                </div> -->
            </div>
            {% endfor %}
            <div class="modal-footer text-muted">
                <span id="answer"></span>
            </div>
        </div>
    </div>
</div>
</main>
{% endblock content %}
{% block extra_scripts %}
    <script>
        $(document).ready(function () {
        //$('#footer').addClass('fixed-bottom');
        });
    </script>
{% endblock extra_scripts %}

quiz/templates/quiz/scripts.html
{% load static %}
  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>
  <script type="text/javascript" src="{% static 'js/quiz.js' %}"></script>